# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: iModelTechCI
  demands: Agent.OS -equals Windows_NT

steps:
- task: NodeTool@0
  displayName: Install Node@14.17.5
  inputs:
    versionSpec: '14.17.5'
    checkLatest: true

- script: node common/scripts/install-run-rush.js install --purge
  displayName: rush install
