name:
  $(Date:yyyy.M.d)$(Rev:.r)

trigger:
- main

pool:
  name: iModelTechCI
  demands: Agent.OS -equals Windows_NT

steps:
- task: NodeTool@0
  displayName: Install Node@14.17.5
  inputs:
    versionSpec: '14.17.5'
    checkLatest: true

- script: node common/scripts/install-run-rush.js install --purge
  displayName: rush install

- script: node common/scripts/install-run-rush.js rebuild -v
  displayName: rush rebuild