name: $(Date:yyyy.M.d)$(Rev:.r)

parameters:
  - name: runRushAudit
    type: boolean
    default: true

trigger: none

pr:
  branches:
    include:
      - main
  drafts: false

variables:
  node18Version: '18.12.0'

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux-node18:
          imageName: 'ubuntu-latest'
          nodeVersion: $(node18Version)
        windows-node18:
          imageName: 'windows-latest'
          nodeVersion: $(node18Version)
    pool:
      vmImage: $(imageName)
    variables:
      - group: iModels Clients 3.0 - Integration Tests - DEV
    workspace:
      clean: all

    steps:
      - template: templates/build-test.yml
        parameters:
          runRushAudit: ${{ parameters.runRushAudit }}

  - job: BuildAndTest mac-node18
    pool:
      name: iModelTechMacArm
      demands:
        - Agent.OS -equals Darwin
    variables:
      - group: iModels Clients 3.0 - Integration Tests - DEV
    workspace:
      clean: all

    steps:
      - template: templates/build-test.yml
        parameters:
          runRushAudit: ${{ parameters.runRushAudit }}
