name:
  $(Date:yyyy.M.d)$(Rev:.r)

parameters:
- name: runRushAudit
  type: boolean
  default: true

trigger: none

variables:
  node18Version: '18.13.0'

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
          nodeVersion: $(node18Version)
        mac:
          imageName: 'macos-latest'
          nodeVersion: $(node18Version)
        windows:
          imageName: 'windows-latest'
          nodeVersion: $(node18Version)
    pool:
        vmImage: $(imageName)
    variables:
      - group: iModels Clients - Integration Tests - DEV
    workspace:
      clean: all

    steps:
    - template: templates/build-test.yml
      parameters:
        runRushAudit: ${{ parameters.runRushAudit }}
