name:
  $(Date:yyyy.M.d)$(Rev:.r)

trigger: none

jobs:
  - job: BuildTestDEVAndPublish
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'
    pool:
        vmImage: $(imageName)
    variables:
      - group: iModels Clients - Integration Tests - DEV
    workspace:
      clean: all

    steps:
    - template: templates/build-test.yml
    - template: templates/publish.yml
