parameters:
- name: runRushAudit
  type: boolean
  default: true

steps:
  - task: NodeTool@0
    displayName: Install Node@14.17.5
    inputs:
      versionSpec: '14.17.5'
      checkLatest: true

  - script: node common/scripts/install-run-rush.js install --purge
    displayName: rush install

  - script: node common/scripts/install-run-rush.js audit
    displayName: rush audit
    condition: and(succeeded(), eq('${{ parameters.runRushAudit }}', true))

  - script: node common/scripts/install-run-rush.js rebuild -v
    displayName: rush rebuild

  - script: node common/scripts/install-run-rush.js lint
    displayName: rush lint

  - script: node common/scripts/install-run-rush.js spell-check
    displayName: rush spell-check

  - script: npm run test:unit
    displayName: npm run test:unit (@itwin/imodels-client-management and @itwin/imodels-client-authoring tests)
    workingDirectory: tests/imodels-clients-tests

  - script: npm run test:integration
    displayName: npm run test:integration (@itwin/imodels-client-management and @itwin/imodels-client-authoring tests)
    workingDirectory: tests/imodels-clients-tests
    env:
      AUTH_CLIENT_ID: $(AUTH_CLIENT_ID)
      AUTH_CLIENT_SECRET: $(AUTH_CLIENT_SECRET)
      TEST_USERS_ADMIN1_EMAIL: $(TEST_USERS_ADMIN1_EMAIL)
      TEST_USERS_ADMIN1_PASSWORD: $(TEST_USERS_ADMIN1_PASSWORD)
      TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL: $(TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL)
      TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD: $(TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD)

  - script: npm run test:integration
    displayName: npm run test:integration (@itwin/imodels-access-frontend tests)
    workingDirectory: tests/imodels-access-frontend-tests
    env:
      AUTH_CLIENT_ID: $(AUTH_CLIENT_ID)
      AUTH_CLIENT_SECRET: $(AUTH_CLIENT_SECRET)
      TEST_USERS_ADMIN1_EMAIL: $(TEST_USERS_ADMIN1_EMAIL)
      TEST_USERS_ADMIN1_PASSWORD: $(TEST_USERS_ADMIN1_PASSWORD)
      TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL: $(TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL)
      TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD: $(TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD)

  - script: npm run test:integration
    displayName: npm run test:integration (@itwin/imodels-access-backend tests)
    workingDirectory: tests/imodels-access-backend-tests
    env:
      AUTH_CLIENT_ID: $(AUTH_CLIENT_ID)
      AUTH_CLIENT_SECRET: $(AUTH_CLIENT_SECRET)
      TEST_USERS_ADMIN1_EMAIL: $(TEST_USERS_ADMIN1_EMAIL)
      TEST_USERS_ADMIN1_PASSWORD: $(TEST_USERS_ADMIN1_PASSWORD)
      TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL: $(TEST_USERS_ADMIN2_FULLY_FEATURED_EMAIL)
      TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD: $(TEST_USERS_ADMIN2_FULLY_FEATURED_PASSWORD)

  - script: node common/scripts/install-run-rush.js publish --pack --include-all --publish
    displayName: rush publish (into .tgz)

  - task: PublishBuildArtifacts@1
    displayName: publish .tgz as build artifacts
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/common/temp/artifacts/packages'
      ArtifactName: packages
