steps:
  - task: NodeTool@0
    displayName: Install Node@14.17.5
    inputs:
      versionSpec: '14.17.5'
      checkLatest: true

  - script: node common/scripts/install-run-rush.js install --purge
    displayName: rush install

  - script: node common/scripts/install-run-rush.js rebuild -v
    displayName: rush rebuild

  - script: node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public
    displayName: rush publish package
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    env:
      NPM_AUTH_TOKEN: $(npmToken)
