steps:
  - task: NodeTool@0
    displayName: Install Node@$(nodeVersion)
    inputs:
      versionSpec: $(nodeVersion)
      checkLatest: true

  - script: node common/scripts/install-run-rush.js install --purge
    displayName: rush install

  - script: node common/scripts/install-run-rush.js rebuild -v
    displayName: rush rebuild

  - name: Configure git
    run: |
      git config --local user.email imodeljs-admin@users.noreply.github.com
      git config --local user.name imodeljs-admin

  - script: node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public --target-branch main
    displayName: rush publish package
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    env:
      NPM_AUTH_TOKEN: $(npmToken)
